# Generated by Django 4.0 on 2021-12-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_visit_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.CharField(max_length=30)),
                ('todate', models.CharField(max_length=30)),
                ('noofguest', models.CharField(max_length=30)),
                ('typeofacc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
